// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	Empty
	Todo
	TodoRequestId
	TodoList
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Todo struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TodoRequestId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *TodoRequestId) Reset()                    { *m = TodoRequestId{} }
func (m *TodoRequestId) String() string            { return proto.CompactTextString(m) }
func (*TodoRequestId) ProtoMessage()               {}
func (*TodoRequestId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TodoRequestId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoList struct {
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *TodoList) Reset()                    { *m = TodoList{} }
func (m *TodoList) String() string            { return proto.CompactTextString(m) }
func (*TodoList) ProtoMessage()               {}
func (*TodoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TodoList) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "todo.Empty")
	proto.RegisterType((*Todo)(nil), "todo.Todo")
	proto.RegisterType((*TodoRequestId)(nil), "todo.TodoRequestId")
	proto.RegisterType((*TodoList)(nil), "todo.TodoList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoService service

type TodoServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodoList, error)
	Create(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*Todo, error)
	Delete(ctx context.Context, in *TodoRequestId, opts ...grpc.CallOption) (*Empty, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodoList, error) {
	out := new(TodoList)
	err := grpc.Invoke(ctx, "/todo.TodoService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Create(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := grpc.Invoke(ctx, "/todo.TodoService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Delete(ctx context.Context, in *TodoRequestId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/todo.TodoService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceServer interface {
	List(context.Context, *Empty) (*TodoList, error)
	Create(context.Context, *Todo) (*Todo, error)
	Delete(context.Context, *TodoRequestId) (*Empty, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Todo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Create(ctx, req.(*Todo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Delete(ctx, req.(*TodoRequestId))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TodoService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TodoService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TodoService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xc4, 0x40,
	0x0c, 0xc6, 0x3b, 0xdd, 0xb6, 0xab, 0x29, 0xee, 0x21, 0x7a, 0x18, 0x7a, 0xb1, 0x04, 0x84, 0x3d,
	0x2c, 0x7b, 0xa8, 0x8f, 0xe0, 0x1f, 0x10, 0x3c, 0x55, 0x5f, 0x40, 0x3b, 0x39, 0x0c, 0xd4, 0x4e,
	0x6d, 0xa3, 0xe0, 0x0b, 0xf8, 0xdc, 0x32, 0x53, 0x8a, 0xc3, 0xde, 0xf2, 0x25, 0xf9, 0xbe, 0xfc,
	0x08, 0x80, 0x38, 0xe3, 0x8e, 0xe3, 0xe4, 0xc4, 0x61, 0xe6, 0x6b, 0xda, 0x42, 0xfe, 0xf0, 0x31,
	0xca, 0x0f, 0x3d, 0x42, 0xf6, 0xea, 0x8c, 0xc3, 0x1d, 0xa4, 0xd6, 0x68, 0x55, 0xab, 0xfd, 0x79,
	0x9b, 0x5a, 0x83, 0x57, 0x90, 0x8b, 0x95, 0x9e, 0x75, 0x1a, 0x5a, 0x8b, 0x40, 0x0d, 0xdb, 0xce,
	0x0d, 0xc2, 0x83, 0xe8, 0x4d, 0xe8, 0xaf, 0x92, 0xae, 0xe1, 0xc2, 0xe7, 0xb4, 0xfc, 0xf9, 0xc5,
	0xb3, 0x3c, 0x99, 0xd3, 0x40, 0x3a, 0xc0, 0x99, 0x5f, 0x78, 0xb6, 0xb3, 0x60, 0x0d, 0xb9, 0xa7,
	0x98, 0xb5, 0xaa, 0x37, 0xfb, 0xb2, 0x81, 0x63, 0xe0, 0x0b, 0xfe, 0x65, 0xd0, 0xfc, 0x2a, 0x28,
	0xbd, 0x7e, 0xe1, 0xe9, 0xdb, 0x76, 0x8c, 0x37, 0x90, 0x05, 0x67, 0xb9, 0xac, 0x06, 0xf6, 0x6a,
	0xf7, 0xef, 0xf3, 0x43, 0x4a, 0x90, 0xa0, 0xb8, 0x9b, 0xf8, 0x4d, 0x18, 0xa3, 0xcc, 0x2a, 0xaa,
	0x29, 0xc1, 0x03, 0x14, 0xf7, 0xdc, 0xb3, 0x30, 0x5e, 0x46, 0x77, 0x57, 0xee, 0x2a, 0xbe, 0x40,
	0xc9, 0x7b, 0x11, 0xbe, 0x76, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x63, 0x8e, 0x9e, 0xab, 0x43,
	0x01, 0x00, 0x00,
}
