// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	ToDo
	Work
	Personal
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	ReadAllRequest
	ReadAllResponse
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Task we have to do
type ToDo struct {
	// Unique integer identifier of the todo task
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Title of the task
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	// Detail description of the todo task
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Types that are valid to be assigned to Tags:
	//	*ToDo_Work
	//	*ToDo_Personal
	Tags isToDo_Tags `protobuf_oneof:"tags"`
	// Date and time to remind the todo task
	Reminder *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=reminder" json:"reminder,omitempty"`
}

func (m *ToDo) Reset()                    { *m = ToDo{} }
func (m *ToDo) String() string            { return proto.CompactTextString(m) }
func (*ToDo) ProtoMessage()               {}
func (*ToDo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isToDo_Tags interface{ isToDo_Tags() }

type ToDo_Work struct {
	Work *Work `protobuf:"bytes,4,opt,name=work,oneof"`
}
type ToDo_Personal struct {
	Personal *Personal `protobuf:"bytes,5,opt,name=personal,oneof"`
}

func (*ToDo_Work) isToDo_Tags()     {}
func (*ToDo_Personal) isToDo_Tags() {}

func (m *ToDo) GetTags() isToDo_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ToDo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToDo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ToDo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ToDo) GetWork() *Work {
	if x, ok := m.GetTags().(*ToDo_Work); ok {
		return x.Work
	}
	return nil
}

func (m *ToDo) GetPersonal() *Personal {
	if x, ok := m.GetTags().(*ToDo_Personal); ok {
		return x.Personal
	}
	return nil
}

func (m *ToDo) GetReminder() *google_protobuf.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ToDo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ToDo_OneofMarshaler, _ToDo_OneofUnmarshaler, _ToDo_OneofSizer, []interface{}{
		(*ToDo_Work)(nil),
		(*ToDo_Personal)(nil),
	}
}

func _ToDo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ToDo)
	// tags
	switch x := m.Tags.(type) {
	case *ToDo_Work:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Work); err != nil {
			return err
		}
	case *ToDo_Personal:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Personal); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ToDo.Tags has unexpected type %T", x)
	}
	return nil
}

func _ToDo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ToDo)
	switch tag {
	case 4: // tags.work
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Work)
		err := b.DecodeMessage(msg)
		m.Tags = &ToDo_Work{msg}
		return true, err
	case 5: // tags.personal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Personal)
		err := b.DecodeMessage(msg)
		m.Tags = &ToDo_Personal{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ToDo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ToDo)
	// tags
	switch x := m.Tags.(type) {
	case *ToDo_Work:
		s := proto.Size(x.Work)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ToDo_Personal:
		s := proto.Size(x.Personal)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Work struct {
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
}

func (m *Work) Reset()                    { *m = Work{} }
func (m *Work) String() string            { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()               {}
func (*Work) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Work) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Personal struct {
	Conscription string `protobuf:"bytes,2,opt,name=conscription" json:"conscription,omitempty"`
	Prescription string `protobuf:"bytes,3,opt,name=prescription" json:"prescription,omitempty"`
}

func (m *Personal) Reset()                    { *m = Personal{} }
func (m *Personal) String() string            { return proto.CompactTextString(m) }
func (*Personal) ProtoMessage()               {}
func (*Personal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Personal) GetConscription() string {
	if m != nil {
		return m.Conscription
	}
	return ""
}

func (m *Personal) GetPrescription() string {
	if m != nil {
		return m.Prescription
	}
	return ""
}

// Request data to create new todo task
type CreateRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Task entity to add
	ToDo *ToDo `protobuf:"bytes,2,opt,name=toDo" json:"toDo,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

// Contains data of created todo task
type CreateResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// ID of created task
	Id int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Request data to read todo task
type ReadRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Unique integer identifier of the todo task
	Id int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains todo task data specified in by ID request
type ReadResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Task entity read by ID
	ToDo *ToDo `protobuf:"bytes,2,opt,name=toDo" json:"toDo,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

// Request data to update todo task
type UpdateRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Task entity to update
	ToDo *ToDo `protobuf:"bytes,2,opt,name=toDo" json:"toDo,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

// Contains status of update operation
type UpdateResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Contains number of entities have beed updated
	// Equals 1 in case of succesfull update
	Updated int64 `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

// Request data to delete todo task
type DeleteRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Unique integer identifier of the todo task to delete
	Id int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains status of delete operation
type DeleteResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Contains number of entities have beed deleted
	// Equals 1 in case of succesfull delete
	Deleted int64 `protobuf:"varint,2,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

// Request data to read all todo task
type ReadAllRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
}

func (m *ReadAllRequest) Reset()                    { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()               {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// Contains list of all todo tasks
type ReadAllResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// List of all todo tasks
	ToDos []*ToDo `protobuf:"bytes,2,rep,name=toDos" json:"toDos,omitempty"`
}

func (m *ReadAllResponse) Reset()                    { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()               {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetToDos() []*ToDo {
	if m != nil {
		return m.ToDos
	}
	return nil
}

func init() {
	proto.RegisterType((*ToDo)(nil), "todo.ToDo")
	proto.RegisterType((*Work)(nil), "todo.Work")
	proto.RegisterType((*Personal)(nil), "todo.Personal")
	proto.RegisterType((*CreateRequest)(nil), "todo.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "todo.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "todo.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "todo.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "todo.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "todo.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "todo.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "todo.DeleteResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "todo.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "todo.ReadAllResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ToDoService service

type ToDoServiceClient interface {
	// Read all todo tasks
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
	// Create new todo task
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Read todo task
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Readv2(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Update todo task
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Delete todo task
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type toDoServiceClient struct {
	cc *grpc.ClientConn
}

func NewToDoServiceClient(cc *grpc.ClientConn) ToDoServiceClient {
	return &toDoServiceClient{cc}
}

func (c *toDoServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := grpc.Invoke(ctx, "/todo.ToDoService/ReadAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/todo.ToDoService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/todo.ToDoService/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Readv2(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/todo.ToDoService/Readv2", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/todo.ToDoService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/todo.ToDoService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToDoService service

type ToDoServiceServer interface {
	// Read all todo tasks
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
	// Create new todo task
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Read todo task
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Readv2(context.Context, *ReadRequest) (*ReadResponse, error)
	// Update todo task
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// Delete todo task
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterToDoServiceServer(s *grpc.Server, srv ToDoServiceServer) {
	s.RegisterService(&_ToDoService_serviceDesc, srv)
}

func _ToDoService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.ToDoService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.ToDoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.ToDoService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Readv2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Readv2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.ToDoService/Readv2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Readv2(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.ToDoService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.ToDoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.ToDoService",
	HandlerType: (*ToDoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAll",
			Handler:    _ToDoService_ReadAll_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ToDoService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ToDoService_Read_Handler,
		},
		{
			MethodName: "Readv2",
			Handler:    _ToDoService_Readv2_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ToDoService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ToDoService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xae, 0x13, 0xd7, 0x0d, 0x27, 0x3f, 0x2d, 0xd3, 0x54, 0x58, 0x11, 0x02, 0x6b, 0x56, 0x51,
	0xd4, 0xd8, 0xad, 0xa9, 0xba, 0x28, 0x5d, 0x34, 0x25, 0x48, 0x05, 0xb1, 0x40, 0xa6, 0x15, 0x12,
	0x3b, 0xd7, 0x1e, 0x1c, 0x53, 0xc7, 0x63, 0x3c, 0x93, 0xa4, 0x08, 0xb1, 0xe1, 0x11, 0x60, 0xc7,
	0xab, 0xb0, 0xe0, 0x21, 0xd8, 0xdf, 0xd5, 0xdd, 0xdf, 0x57, 0xb8, 0xf2, 0x8c, 0x27, 0xa9, 0x93,
	0xa6, 0xf7, 0x4a, 0x77, 0x93, 0xcc, 0x9c, 0xf3, 0xcd, 0xf7, 0x7d, 0xe7, 0x47, 0x09, 0x00, 0xa7,
	0x21, 0xb5, 0xb3, 0x9c, 0x72, 0x8a, 0xf4, 0xe2, 0xdc, 0xfb, 0x3c, 0xa2, 0x34, 0x4a, 0x88, 0x23,
	0x62, 0xf7, 0xb3, 0x9f, 0x1d, 0x1e, 0x4f, 0x09, 0xe3, 0xfe, 0x34, 0x93, 0xb0, 0xde, 0xa7, 0x25,
	0xc0, 0xcf, 0x62, 0xc7, 0x4f, 0x53, 0xca, 0x7d, 0x1e, 0xd3, 0x94, 0x95, 0xd9, 0x63, 0xf1, 0x15,
	0x0c, 0x23, 0x92, 0x0e, 0xd9, 0xc2, 0x8f, 0x22, 0x92, 0x3b, 0x34, 0x13, 0x88, 0x4d, 0x34, 0x7e,
	0xa5, 0x81, 0x7e, 0x4b, 0xc7, 0x14, 0x75, 0xa0, 0x16, 0x87, 0xa6, 0x66, 0x69, 0xfd, 0xba, 0x57,
	0x8b, 0x43, 0xd4, 0x85, 0x5d, 0x1e, 0xf3, 0x84, 0x98, 0x35, 0x4b, 0xeb, 0x7f, 0xe4, 0xc9, 0x0b,
	0xb2, 0xa0, 0x19, 0x12, 0x16, 0xe4, 0xb1, 0x20, 0x34, 0xeb, 0x22, 0xf7, 0x34, 0x84, 0x2c, 0xd0,
	0x17, 0x34, 0x7f, 0x30, 0x75, 0x4b, 0xeb, 0x37, 0x5d, 0xb0, 0x45, 0x79, 0x3f, 0xd2, 0xfc, 0xe1,
	0x66, 0xc7, 0x13, 0x19, 0x74, 0x0c, 0x8d, 0x8c, 0xe4, 0x8c, 0xa6, 0x7e, 0x62, 0xee, 0x0a, 0x54,
	0x47, 0xa2, 0xbe, 0x2f, 0xa3, 0x37, 0x3b, 0xde, 0x12, 0x81, 0xce, 0xa1, 0x91, 0x93, 0x69, 0x9c,
	0x86, 0x24, 0x37, 0x0d, 0x81, 0xee, 0xd9, 0xb2, 0x7e, 0x5b, 0x35, 0xc8, 0xbe, 0x55, 0x0d, 0xf2,
	0x96, 0xd8, 0x6b, 0x03, 0x74, 0xee, 0x47, 0x0c, 0xf7, 0x41, 0x2f, 0xd4, 0xd7, 0x9d, 0x6b, 0x1b,
	0xce, 0xb1, 0x07, 0x0d, 0xe5, 0x00, 0x61, 0x68, 0x05, 0x34, 0x5d, 0xc1, 0x65, 0x13, 0x2a, 0xb1,
	0x02, 0x93, 0xe5, 0x1b, 0xcd, 0xa8, 0xc4, 0xf0, 0x08, 0xda, 0x5f, 0xe5, 0xc4, 0xe7, 0xc4, 0x23,
	0xbf, 0xce, 0x08, 0xe3, 0xe8, 0x00, 0xea, 0x7e, 0x16, 0x97, 0xf2, 0xc5, 0x11, 0x7d, 0x06, 0x3a,
	0xa7, 0x63, 0x2a, 0x24, 0x96, 0x0d, 0x2b, 0x46, 0xe2, 0x89, 0x38, 0x76, 0xa1, 0xa3, 0x28, 0x58,
	0x46, 0x53, 0x46, 0x9e, 0xe1, 0x90, 0xc3, 0xab, 0xa9, 0xe1, 0x61, 0x07, 0x9a, 0x1e, 0xf1, 0xc3,
	0xed, 0xa2, 0xeb, 0x0f, 0xae, 0xa0, 0x25, 0x1f, 0x6c, 0x95, 0x78, 0x97, 0xcd, 0x11, 0xb4, 0xef,
	0xb2, 0xf0, 0x83, 0x2a, 0xbd, 0x84, 0x8e, 0xa2, 0xd8, 0x6a, 0xc3, 0x84, 0xbd, 0x99, 0xc0, 0x28,
	0xf7, 0xea, 0x8a, 0x4f, 0xa1, 0x3d, 0x26, 0x09, 0x79, 0xc9, 0xc0, 0x7a, 0xd5, 0x97, 0xd0, 0x51,
	0x4f, 0x5e, 0x12, 0x0c, 0x05, 0x66, 0x29, 0x58, 0x5e, 0x31, 0x86, 0x4e, 0xd1, 0xb3, 0x51, 0x92,
	0x6c, 0x55, 0xc4, 0x5f, 0xc3, 0xfe, 0x12, 0xb3, 0x55, 0xc2, 0x82, 0xdd, 0xa2, 0x7e, 0x66, 0xd6,
	0xac, 0xfa, 0x5a, 0x63, 0x64, 0xc2, 0x7d, 0x53, 0x87, 0x66, 0x71, 0xff, 0x81, 0xe4, 0xf3, 0x38,
	0x20, 0xe8, 0x3b, 0xd8, 0x2b, 0x69, 0x51, 0x57, 0xa2, 0xab, 0x4e, 0x7a, 0x47, 0x6b, 0x51, 0xa9,
	0x8d, 0xbb, 0x7f, 0xfe, 0xff, 0xfa, 0xef, 0x5a, 0x07, 0xb5, 0x9c, 0xf9, 0xa9, 0x53, 0x20, 0x1c,
	0x3f, 0x49, 0xd0, 0x0d, 0x18, 0x72, 0xc3, 0xd0, 0xa1, 0x7c, 0x56, 0x59, 0xd9, 0x5e, 0xb7, 0x1a,
	0x2c, 0xa9, 0x0e, 0x05, 0x55, 0x1b, 0x37, 0x14, 0xd5, 0x85, 0x36, 0x40, 0x63, 0xd0, 0x0b, 0x49,
	0xf4, 0xf1, 0x4a, 0x5e, 0xb1, 0xa0, 0xa7, 0xa1, 0x92, 0xe3, 0x48, 0x70, 0xec, 0xa3, 0xf6, 0xd2,
	0xce, 0xef, 0x71, 0xf8, 0x07, 0xfa, 0x06, 0x8c, 0x02, 0x36, 0x77, 0xdf, 0x97, 0xc7, 0x14, 0x3c,
	0x08, 0xb7, 0x9d, 0xb9, 0xbb, 0xe2, 0x29, 0x0c, 0x3d, 0x80, 0x21, 0x57, 0x4a, 0x95, 0x56, 0xd9,
	0x51, 0x55, 0x5a, 0x75, 0xeb, 0xf0, 0xb9, 0xa0, 0x3b, 0xe9, 0xa1, 0x95, 0xad, 0x62, 0x0c, 0xb6,
	0xe4, 0xfc, 0xe9, 0x13, 0xf7, 0xf9, 0x04, 0xfa, 0x16, 0x0c, 0xb9, 0x4e, 0x4a, 0xac, 0xb2, 0x8f,
	0x4a, 0xac, 0xba, 0x71, 0xaa, 0x07, 0x83, 0x6a, 0x0f, 0xae, 0xff, 0xd3, 0xfe, 0x1a, 0xfd, 0xab,
	0xa1, 0x3b, 0x68, 0x15, 0x73, 0xb7, 0x98, 0x1c, 0x3c, 0xbe, 0x82, 0xfd, 0x88, 0x0e, 0xa3, 0x3c,
	0x0b, 0x86, 0xe4, 0xd1, 0x9f, 0x66, 0x09, 0x41, 0xc3, 0x09, 0xe7, 0x19, 0xbb, 0x70, 0x9c, 0x28,
	0xe6, 0x93, 0xd9, 0xbd, 0x1d, 0xd0, 0xa9, 0xb3, 0xf0, 0xe7, 0xe4, 0xb7, 0xe2, 0x83, 0x39, 0x6b,
	0x70, 0xb7, 0x7e, 0x6a, 0x9f, 0x0c, 0x34, 0xcd, 0x3d, 0xf0, 0xb3, 0x2c, 0x89, 0x03, 0xf1, 0x67,
	0xe0, 0xfc, 0xc2, 0x68, 0x7a, 0xb1, 0x11, 0xf1, 0xbe, 0x84, 0xfa, 0xd9, 0xc9, 0x19, 0x3a, 0x83,
	0x81, 0x47, 0xf8, 0x2c, 0x4f, 0x49, 0x68, 0x2d, 0x26, 0x24, 0xb5, 0xf8, 0x84, 0x58, 0x39, 0x61,
	0x74, 0x96, 0x07, 0xc4, 0x0a, 0x29, 0x61, 0x56, 0x4a, 0xb9, 0x45, 0x1e, 0x63, 0xc6, 0x6d, 0x64,
	0x80, 0xfe, 0x4f, 0x4d, 0xdb, 0xbb, 0x37, 0xc4, 0xcf, 0xf3, 0x17, 0x6f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x59, 0xdd, 0x1e, 0xdc, 0xe1, 0x06, 0x00, 0x00,
}
